rootPath = /home/user/Desktop/host-se1/se1
incPath = $(rootPath)/includes
libsPath = $(rootPath)/libs

LIBGCC = /usr/local/arm-tools/arm-2009q1/lib/gcc/arm-none-eabi/4.3.3/libgcc.a
LDSCRIPT = /home/user/Desktop/host-se1/se1/bsp/ldscript_ram

ARM = arm-none-eabi-

Ainsight = $(ARM)insight
Agcc = $(ARM)gcc
Ald = $(ARM)ld
